/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    BuyFlow: typeof import('./src/components/BuyFlow.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    OrderHistory: typeof import('./src/components/OrderHistory.vue')['default']
    OrdersTable: typeof import('./src/components/OrdersTable.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    SearchSecurities: typeof import('./src/components/SearchSecurities.vue')['default']
    SecurityDetails: typeof import('./src/components/SecurityDetails.vue')['default']
    SecurityList: typeof import('./src/components/SecurityList.vue')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    WatchList: typeof import('./src/components/WatchList.vue')['default']
  }
}
